//use std::rc::Rc;
use std::sync::Arc;

use crate::t0pology::PackTopology;
///
///You can switch from Rc to Arc
pub type InFile<T> = Arc<Box<[T]>>;
//pub type InFile<T> = Arc<Vec<T>>;

#[derive(Debug, Clone)]
///use in handmaker
pub enum AtomHandFile {
    ///the file size generated by the session initiator and received by the passive
    /// participant
    InitiatorFileSize(usize),
    ///the file size generated by a passive session participant, and they accept this
    /// file and the session
    PassiveFileSize(usize),
}

impl AtomHandFile {
    /// Returns `true` if the variant is `InitiatorFileSize`.
    pub fn is_initiator(&self) -> bool {
        matches!(self, Self::InitiatorFileSize(_))
    }

    /// Returns `true` if the variant is `PassiveFileSize`.
    pub fn is_passive(&self) -> bool {
        matches!(self, Self::PassiveFileSize(_))
    }

    /// Returns the inner `usize` value regardless of the variant.
    pub fn size(&self) -> usize {
        match self {
            Self::InitiatorFileSize(s) | Self::PassiveFileSize(s) => *s,
        }
    }
}

impl PartialEq for AtomHandFile {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::InitiatorFileSize(a), Self::InitiatorFileSize(b)) => a == b,
            (Self::PassiveFileSize(a), Self::PassiveFileSize(b)) => a == b,
            _ => false,
        }
    }
}

/*

#[derive(Debug, Clone)]
///list of errors
pub enum PackErr {
    ///
    IdConnErr(&'static str),
    ///
    IdSendRecvErr(&'static str),
    ///
    CrcErr(&'static str),
    ///
    TagErr(&'static str),
    ///
    LenErr(&'static str),
    ///
    UndefinedErr(&'static str),
    ///
    TTLErr(&'static str),
}
*/
#[derive(Debug, Clone)]
///
pub enum WTypeErr {
    ///
    LenSizeErr(&'static str),
    ///
    CompileFieldsErr(&'static str),
    ///
    PackageDamaged(&'static str),
    ///WorkTimeErr: various types of errors for which there is no solution
    WorkTimeErr(&'static str),
}

#[cfg_attr(test, derive(Debug))]
///
pub enum WSQueueErr {
    ///
    NonCritical(&'static str),
    ///
    Critical(&'static str),
}

impl WSQueueErr {
    ///
    pub fn is_critical(&self) -> bool {
        match self {
            Self::Critical(_) => true,
            Self::NonCritical(_) => false,
        }
    }
    ///
    pub fn is_non_critical(&self) -> bool {
        match self {
            Self::Critical(_) => false,
            Self::NonCritical(_) => true,
        }
    }
}

impl PartialEq for WSQueueErr {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::NonCritical(x), Self::NonCritical(y)) => x == y,
            (Self::Critical(x), Self::Critical(y)) => x == y,
            _ => false,
        }
    }
}

/*

impl PartialEq for PackErr {
    fn eq(&self, other: &Self) -> bool {
        matches!(
            (self, other),
            (Self::IdConnErr(_), Self::IdConnErr(_))
                | (Self::IdSendRecvErr(_), Self::IdSendRecvErr(_))
                | (Self::CrcErr(_), Self::CrcErr(_))
                | (Self::TagErr(_), Self::TagErr(_))
                | (Self::LenErr(_), Self::LenErr(_))
                | (Self::UndefinedErr(_), Self::UndefinedErr(_))
                | (Self::TTLErr(_), Self::TTLErr(_))
        )
    }
}
*/

impl WTypeErr {
    ///
    pub fn is_len_small_err(&self) -> bool {
        matches!(self, Self::LenSizeErr(_))
    }
    ///
    pub fn is_none_field(&self) -> bool {
        match self {
            Self::CompileFieldsErr(_) => true,
            _ => false,
        }
    }
    ///
    // pub fn is_pascage_damaget(&self) -> bool {
    //     matches!(self, Self::PackageDamaged(_))
    // }
    ///
    //pub fn is_work_time_err(&self) -> bool {
    //    matches!(self, Self::WorkTimeErr(_))
    //}
    ///
    pub fn err_to_str(&self) -> &'static str {
        match self {
            Self::LenSizeErr(x) => x,
            Self::CompileFieldsErr(x) => x,
            Self::PackageDamaged(x) => x,
            Self::WorkTimeErr(x) => x,
        }
    }
}

impl PartialEq for WTypeErr {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::LenSizeErr(x), Self::LenSizeErr(y)) => x == y,
            (Self::CompileFieldsErr(x), Self::CompileFieldsErr(y)) => x == y,
            (Self::PackageDamaged(x), Self::PackageDamaged(y)) => x == y,
            (Self::WorkTimeErr(x), Self::WorkTimeErr(y)) => x == y,
            _ => false,
        }
    }
}
///
#[derive(Debug, Clone)]
pub enum MyRole {
    ///
    Initiator,
    ///
    Passive,
}
impl MyRole {
    ///
    pub fn is_initiator(&self) -> bool {
        matches!(self, Self::Initiator)
    }
    ///
    pub fn is_passive(&self) -> bool {
        matches!(self, Self::Passive)
    }
    ///
    pub fn sate_to_bit(&self) -> u8 {
        match self {
            Self::Passive => 0,
            Self::Initiator => 1,
        }
    }
    ///
    pub fn bit_to_state(bit: u8) -> Self {
        match bit & 1 {
            1 => Self::Initiator,
            0 => Self::Passive,
            _ => Self::Initiator,
        }
    }
}

impl PartialEq for MyRole {
    fn eq(&self, other: &Self) -> bool {
        matches!(
            (self, other),
            (Self::Initiator, Self::Initiator) | (Self::Passive, Self::Passive)
        )
    }
}

#[derive(Debug, Clone)]
///
pub enum PackType {
    ///
    FBack,
    ///
    Data,
}
impl PackType {
    ///
    pub fn is_data(&self) -> bool {
        matches!(self, Self::Data)
    }
    ///
    pub fn is_fback(&self) -> bool {
        matches!(self, Self::FBack)
    }
    ///
    pub fn sate_to_bit(&self) -> u8 {
        match self {
            Self::FBack => 1,
            Self::Data => 0,
        }
    }
    ///
    pub fn bit_to_state(bit: u8) -> Self {
        match bit & 1 {
            1 => Self::FBack,
            0 => Self::Data,
            _ => Self::FBack,
        }
    }
}

impl PartialEq for PackType {
    fn eq(&self, other: &Self) -> bool {
        matches!(
            (self, other),
            (Self::Data, Self::Data) | (Self::FBack, Self::FBack)
        )
    }
}

//======================================================================================================

/*type1 fn(&[u8], &mut [u8], &mut [u8],u64, Option<&[u8]>) -> Result<(), &'static str>
where &[u8] is the head, the data that is not encrypted,
the first &mut [u8] is the body, the data that is encrypted
the second &mut [u8] is the place where the authentication tag from head + body should be placed
Option<&[u8]> is a Nonce if is a init in topology: &t2page::PackTopology,

type 2 fn(&mut[u8],usize,usize, u64, Option<&[u8]>) -> Result<(), &'static str>
&mut[u8] is the full mutable packet
the first usize is the index of the start of the body, so [0..(first usize)] is the head
the second usize is the index of the start of tag, so [(first usize)..(second usize)] is the body
the tag field, it is [(second usize)..] is the place for the tag
Option<&[u8]> is a Nonce if is a init in topology: &t2page::PackTopology,

this enum is needed for maximum compatibility with the encryption libraries that are on the rust
they both return -> Result<(), &'static str>
ok() means that the data was encrypted successfully
and there were no errors, &'static str reports some error,
 when it is called, the preparation of the packet for sending
 will be interrupted and it will not be sent

#[derive(Debug, Clone)]
pub enum TypeGetMode {
    /// (HEAD non enc), (PAYLOAD enc), (TAG) (countr(nonce)), (NONCE)
    Type1SplitMutSlices(
        fn(&[u8], &mut [u8], &mut [u8], u64, Option<&[u8]>) -> Result<(), &'static str>,
    ),
    /// (FULLDATA),  (HEAD non enc)[0..usize1],(PAYLOAD
    /// enc)[usize1..usize2],(TAG)[usize2..],(countr(nonce)), (NONCE)[start..end]
    Type2FullArrAndIndexes(
        fn(&mut [u8], usize, usize, u64, Option<(usize, usize)>) -> Result<(), &'static str>,
    ),
}
    */

#[derive(Debug, Clone)]
///
pub enum Cryptlag {
    ///
    Encrypt,
    ///
    Decrypt,
}
#[derive(Debug, Clone)]
///
pub enum StatusDecrypt {
    ///
    PackageDamaged,
    ///
    DecodedCorrectly,
}

impl StatusDecrypt {
    ///
    pub fn is_correctly(&self) -> bool {
        matches!(self, Self::DecodedCorrectly)
    }

    ///
    pub fn is_damaged(&self) -> bool {
        matches!(self, Self::PackageDamaged)
    }
}

impl PartialEq for StatusDecrypt {
    fn eq(&self, other: &Self) -> bool {
        matches!(
            (self, other),
            (Self::DecodedCorrectly, Self::DecodedCorrectly)
                | (Self::PackageDamaged, Self::PackageDamaged)
        )
    }
}

//#############################################################3
///
pub trait EncWis: Sized {
    ///
    fn new(key: &[u8]) -> Result<Self, &'static str>;

    /// (HEAD non enc), (PAYLOAD enc), (TAG) (countr(nonce)), (NONCE)
    fn encrypt(
        &self,
        non_enc_head: &[u8],
        enc_payload: &mut [u8],
        auth_tag: &mut [u8],
        nonce_countr: u64,
        nonce: Option<&[u8]>,
    ) -> Result<(), &'static str>;
    /// (HEAD non enc), (PAYLOAD enc), (TAG) (countr(nonce)), (NONCE)
    fn decrypt(
        &self,
        non_enc_head: &[u8],
        enc_payload: &mut [u8],
        auth_tag: &mut [u8],
        nonce_countr: u64,
        nonce: Option<&[u8]>,
    ) -> Result<StatusDecrypt, &'static str>;
}
///
pub trait Noncer: Sized {
    ///
    fn new(seed: &[u8]) -> Result<Self, &'static str>;
    ///

    fn set_nonce(&mut self, nonce_gener: &mut [u8]) -> Result<(), &'static str>;
}
///
pub trait Thrasher: Sized {
    ///
    fn new(seed: &[u8]) -> Result<Self, &'static str>;
    ///

    fn set_user_field(&mut self, user_field: &mut [u8], countr: &u64) -> Result<(), &'static str>;
}
///
pub trait Cfcser: Sized {
    ///
    fn new(seed: &[u8]) -> Result<Self, &'static str>;
    ///
    fn gen_crc(&mut self, payload: &[u8], crc_field: &mut [u8]) -> Result<(), &'static str>;
}
///
pub trait Randomer: Sized {
    ///
    fn new(seed: &[u8]) -> Result<Self, &'static str>;
    ///
    fn gen_rand_u64(&mut self) -> u64;
    ///
    fn gen_rand_u32(&mut self) -> u32;
}
///It's too complicated to explain. I hope I don't forget to add this as an example for
/// clarity.
pub trait HandMaker: Sized {
    ///
    fn new(my_role: MyRole, seed: &[u8]) -> Result<Self, &'static str>;
    ///
    fn file_sheme(&self) -> &[AtomHandFile];
    ///
    fn send(&mut self) -> Result<InFile<u8>, &'static str>;
    ///
    fn recv(&mut self, file: InFile<u8>) -> Result<(), &'static str>;
    ///
    fn get_private_key(&mut self) -> Result<Box<[u8]>, &'static str>;
}
///Be sure to use it in production once before configuring your algorithm to verify that
/// HandMaker is working properly.
pub fn hand_maker_tester<Thm: HandMaker + Clone>() -> Result<(), &'static str> {
    for k_len in [0, 17, 80] {
        for gamma in [0, 77, 255] {
            let mut intua = Thm::new(MyRole::Initiator, &vec![gamma; k_len])?;

            let mut passve = Thm::new(MyRole::Passive, &vec![gamma; k_len])?;

            if !intua.file_sheme()[0].is_initiator() {
                #[cfg(test)]
                {
                    println!("Initiator:   {:?}", intua.file_sheme());
                }
                return Err(
                    "error in initiator in file_sheme()[0], initiator must always send data first!",
                );
            }
            if !passve.file_sheme()[0].is_initiator() {
                #[cfg(test)]
                {
                    println!("Passive:   {:?}", passve.file_sheme());
                }
                return Err(
                    "error in passive in file_sheme()[0], initiator must always send data first!",
                );
            }

            let p_s = passve.file_sheme().to_vec().into_boxed_slice();
            let i_s = intua.file_sheme().to_vec().into_boxed_slice();

            if p_s != i_s {
                #[cfg(test)]
                {
                    println!("Initiator: {:?}", i_s);
                    println!("Passive:   {:?}", p_s);
                }
                return Err(
                    "file_sheme() of the initiator differs from file_sheme() of the passive",
                );
            }

            for cur in p_s {
                #[cfg(test)]
                {
                    println!();
                    println!();
                    println!("len seed: {} , fill seed {} , cur {:?}", k_len, gamma, cur);
                }
                if cur.is_initiator() {
                    let mut temp_passive = passve.clone();
                    //
                    passve.recv(intua.send()?)?;

                    //ivverse test
                    if temp_passive.send().is_ok() {
                        return Err("Passive send() returned the correct value when the \
                                    Initiator send() was in the queue at that moment");
                    }
                } else {
                    let mut temp_init = intua.clone();
                    //
                    intua.recv(passve.send()?)?;
                    //inverse test

                    if temp_init.send().is_ok() {
                        return Err("Initiator send() returned the correct value when the \
                                    Passive send() was in the queue at that moment");
                    }
                }
            }

            let i_pas = intua.get_private_key()?;
            let p_pas = passve.get_private_key()?;

            if i_pas != p_pas {
                #[cfg(test)]
                {
                    println!("Initiator: {:?}", i_pas);
                    println!("Passive:   {:?}", p_pas);
                }
                return Err("At the end of the exchange of all files, 
                when generating the final private key,
                the initiator and passive keys do not match");
            }
        }
    }

    Ok(())
}

///(array(head fields len + headbyte len + payload len+ tag len),(payload start pos,
/// payload endpos) )
pub fn pre_alloc(
    topology: &PackTopology,
    mtu: usize,
    payloadlen: usize,
    fill: u8,
) -> Result<(Box<[u8]>, (usize, usize)), WTypeErr> {
    let len_pack = topology
        .total_minimal_len()
        .checked_add(payloadlen)
        .ok_or(WTypeErr::LenSizeErr("overflow payloadlen + minimal_len()"))?;

    Ok((
        vec![
            fill;
            if len_pack > mtu {
                return Err(WTypeErr::LenSizeErr("len_pack > mtu"));
            } else {
                len_pack
            }
        ]
        .into_boxed_slice(),
        (topology.content_start_pos(), len_pack - topology.tag_len()),
    ))
}

#[cfg(test)]
mod tests_my_role {
    use super::*;

    #[test]
    fn test_is_initiator() {
        assert!(MyRole::Initiator.is_initiator());
        assert!(!MyRole::Passive.is_initiator());
    }

    #[test]
    fn test_is_passive() {
        assert!(MyRole::Passive.is_passive());
        assert!(!MyRole::Initiator.is_passive());
    }

    #[test]
    fn test_state_to_bit() {
        assert_eq!(MyRole::Passive.sate_to_bit(), 0);
        assert_eq!(MyRole::Initiator.sate_to_bit(), 1);
    }

    #[test]
    fn test_bit_to_state() {
        assert!(matches!(MyRole::bit_to_state(0), MyRole::Passive));
        assert!(matches!(MyRole::bit_to_state(1), MyRole::Initiator));
        assert!(matches!(MyRole::bit_to_state(2), MyRole::Passive)); // 2 & 1 = 0
        assert!(matches!(MyRole::bit_to_state(3), MyRole::Initiator)); // 3 & 1 = 1
        assert!(matches!(MyRole::bit_to_state(255), MyRole::Initiator)); // 255 & 1 = 1
    }

    #[test]
    fn test_partial_eq() {
        assert_eq!(MyRole::Initiator, MyRole::Initiator);
        assert_eq!(MyRole::Passive, MyRole::Passive);
        assert_ne!(MyRole::Initiator, MyRole::Passive);
        assert_ne!(MyRole::Passive, MyRole::Initiator);
    }

    #[test]
    fn test_clone() {
        let role1 = MyRole::Initiator;
        let role2 = role1.clone();
        assert_eq!(role1, role2);

        let role3 = MyRole::Passive;
        let role4 = role3.clone();
        assert_eq!(role3, role4);
    }

    #[test]
    fn test_debug() {
        let initiator = format!("{:?}", MyRole::Initiator);
        let passive = format!("{:?}", MyRole::Passive);

        assert!(initiator.contains("Initiator"));
        assert!(passive.contains("Passive"));
    }

    #[test]
    fn test_roundtrip_conversion() {
        // Test that bit_to_state is the inverse of state_to_bit
        for role in [MyRole::Initiator, MyRole::Passive] {
            let bit = role.sate_to_bit();
            let reconstructed = MyRole::bit_to_state(bit);
            assert_eq!(role, reconstructed);
        }
    }
}

#[cfg(test)]
mod tests_my_type {
    use super::*;

    #[test]
    fn test_is_data() {
        assert!(PackType::Data.is_data());
        assert!(!PackType::FBack.is_data());
    }

    #[test]
    fn test_is_fback() {
        assert!(PackType::FBack.is_fback());
        assert!(!PackType::Data.is_fback());
    }

    #[test]
    fn test_sate_to_bit() {
        assert_eq!(PackType::FBack.sate_to_bit(), 1);
        assert_eq!(PackType::Data.sate_to_bit(), 0);
    }

    #[test]
    fn test_bit_to_state() {
        assert!(matches!(PackType::bit_to_state(0), PackType::Data));
        assert!(matches!(PackType::bit_to_state(1), PackType::FBack));
        // Test with higher bits (only LSB should matter)
        assert!(matches!(PackType::bit_to_state(2), PackType::Data)); // 2 & 1 = 0
        assert!(matches!(PackType::bit_to_state(3), PackType::FBack)); // 3 & 1 = 1
        assert!(matches!(PackType::bit_to_state(255), PackType::FBack)); // 255 & 1 = 1
    }

    #[test]
    fn test_partial_eq() {
        assert_eq!(PackType::Data, PackType::Data);
        assert_eq!(PackType::FBack, PackType::FBack);
        assert_ne!(PackType::Data, PackType::FBack);
        assert_ne!(PackType::FBack, PackType::Data);
    }

    #[test]
    fn test_clone() {
        let data = PackType::Data;
        let cloned = data.clone();
        assert_eq!(data, cloned);

        let fback = PackType::FBack;
        let cloned_fback = fback.clone();
        assert_eq!(fback, cloned_fback);
    }
}

#[cfg(test)]
mod tests_prealocc {
    use super::*;
    use crate::t0pology::PackFields;
    #[test]
    fn test_prealoc() {
        let mkd = [13, 7, 6, 8];
        let fields = vec![
            //t2page::PackFields::HeadByte,
            PackFields::UserField(mkd[0]),
            PackFields::Counter(mkd[1]),
            PackFields::IdConnect(mkd[2]),
            PackFields::HeadCRC(mkd[3]),
        ];

        let result = PackTopology::new(19, &fields, true, false).unwrap();

        //let mut temp = pre_alloc(&result, 1000, 500).unwrap();
        let total: usize = mkd.iter().sum();

        assert_eq!(
            pre_alloc(&result, total + 50 + 19, 50, 0),
            Err(WTypeErr::LenSizeErr("len_pack > mtu"))
        );
        assert_eq!(
            pre_alloc(&result, total + 50 + 19, 49, 0),
            Ok((
                vec![
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]
                .into_boxed_slice(),
                (35usize, 84usize)
            ))
        );

        assert_eq!(
            pre_alloc(&result, total + 50 + 19, 49, 99),
            Ok((
                vec![
                    99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
                    99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
                    99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
                    99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
                    99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
                    99, 99, 99
                ]
                .into_boxed_slice(),
                (35usize, 84usize)
            ))
        );

        assert_eq!(
            pre_alloc(&result, !0_usize, (!0_usize) - 1, 0),
            Err(WTypeErr::LenSizeErr("overflow payloadlen + minimal_len()"))
        );

        let mut t = pre_alloc(&result, 100000, 43, 0).unwrap();
        t.0[t.1.0..t.1.1].fill(1);
        let count = t.0.iter().filter(|&&element| element == 1).count();
        let count0 = t.0.iter().take_while(|&&x| x == 0).count();

        assert_eq!(count, 43);
        assert_eq!(count0, result.total_head_slice().2 + 1);

        println!("{:?}   /n{} /n {}", t.0, count, count0);
    }
}

#[cfg(test)]
mod tests_statusdecrypt {
    use super::*;

    // ┌────────────────────────────────────────────────────────────────────────────┐
    // │ group 1: creation & debug/clone traits (auto-derived)                     │
    // └────────────────────────────────────────────────────────────────────────────┘
    #[test]
    fn debug_and_clone_work() {
        let original = StatusDecrypt::DecodedCorrectly;
        let cloned = original.clone();
        assert!(format!("{:?}", cloned).contains("DecodedCorrectly"));
    }

    // ┌────────────────────────────────────────────────────────────────────────────┐
    // │ group 2: equality (PartialEq) – both variants compare correctly          │
    // └────────────────────────────────────────────────────────────────────────────┘
    #[test]
    fn decoded_correctly_equals_itself() {
        assert_eq!(
            StatusDecrypt::DecodedCorrectly,
            StatusDecrypt::DecodedCorrectly
        );
    }

    #[test]
    fn package_damaged_equals_itself() {
        assert_eq!(StatusDecrypt::PackageDamaged, StatusDecrypt::PackageDamaged);
    }

    #[test]
    fn different_variants_are_not_equal() {
        assert_ne!(
            StatusDecrypt::DecodedCorrectly,
            StatusDecrypt::PackageDamaged
        );
    }

    // ┌────────────────────────────────────────────────────────────────────────────┐
    // │ group 3: helper methods (is_correctly / is_damaged) – one test per variant│
    // └────────────────────────────────────────────────────────────────────────────┘
    #[test]
    fn is_correctly_returns_true_only_for_decoded_correctly() {
        assert!(StatusDecrypt::DecodedCorrectly.is_correctly());
        assert!(!StatusDecrypt::PackageDamaged.is_correctly());
    }

    #[test]
    fn is_damaged_returns_true_only_for_package_damaged() {
        assert!(StatusDecrypt::PackageDamaged.is_damaged());
        assert!(!StatusDecrypt::DecodedCorrectly.is_damaged());
    }

    // ┌────────────────────────────────────────────────────────────────────────────┐
    // │ group 4: exhaustive coverage – one test verifies all discriminant values  │
    // └────────────────────────────────────────────────────────────────────────────┘
    #[test]
    fn all_variants_covered() {
        // this test ensures we haven't missed any variant if the enum grows
        let variants = [
            StatusDecrypt::DecodedCorrectly,
            StatusDecrypt::PackageDamaged,
        ];
        for v in variants {
            match v {
                StatusDecrypt::DecodedCorrectly => assert!(v.is_correctly()),
                StatusDecrypt::PackageDamaged => assert!(v.is_damaged()),
            }
        }
    }
}

/*
#[cfg(test)]
mod tests_pack_err {
    use super::*;

    // ┌────────────────────────────────────────────────────────────────────────────┐
    // │ packerr partialeq – equality depends only on variant, not on string       │
    // └────────────────────────────────────────────────────────────────────────────┘

    #[test]
    fn same_variant_with_different_strings_are_equal() {
        // any two strings inside the same variant compare as equal
        assert_eq!(PackErr::IdConnErr("a"), PackErr::IdConnErr("b"));
        assert_eq!(PackErr::IdSendRecvErr("x"), PackErr::IdSendRecvErr("y"));
        assert_eq!(PackErr::CrcErr("foo"), PackErr::CrcErr("bar"));
        assert_eq!(PackErr::TagErr("1"), PackErr::TagErr("2"));
        assert_eq!(PackErr::LenErr("short"), PackErr::LenErr("long"));
        assert_eq!(PackErr::UndefinedErr("?"), PackErr::UndefinedErr("!"));
        assert_eq!(PackErr::TTLErr("127"), PackErr::TTLErr("255"));
    }

    #[test]
    fn same_variant_with_identical_strings_are_equal() {
        // sanity check – identical strings are obviously equal
        assert_eq!(PackErr::IdConnErr("same"), PackErr::IdConnErr("same"));
    }

    #[test]
    fn different_variants_are_not_equal() {
        // every pair of different variants must compare as not equal
        let all_variants = [
            PackErr::IdConnErr(""),
            PackErr::IdSendRecvErr(""),
            PackErr::CrcErr(""),
            PackErr::TagErr(""),
            PackErr::LenErr(""),
            PackErr::UndefinedErr(""),
            PackErr::TTLErr(""),
        ];

        for (i, a) in all_variants.iter().enumerate() {
            for (j, b) in all_variants.iter().enumerate() {
                if i == j {
                    assert_eq!(a, b, "same variant {:?} should equal itself", a);
                } else {
                    assert_ne!(
                        a, b,
                        "different variants {:?} and {:?} must not be equal",
                        a, b
                    );
                }
            }
        }
    }

    #[test]
    fn equality_is_symmetric() {
        let a = PackErr::CrcErr("left");
        let b = PackErr::CrcErr("right");
        assert_eq!(a, b);
        assert_eq!(b, a); // symmetry property
    }

    #[test]
    fn equality_is_transitive() {
        let a = PackErr::TagErr("first");
        let b = PackErr::TagErr("second");
        let c = PackErr::TagErr("third");
        assert_eq!(a, b);
        assert_eq!(b, c);
        assert_eq!(a, c); // transitivity holds because all are same variant
    }

    #[test]
    fn equality_with_self_always_true() {
        let err = PackErr::LenErr("self");
        assert_eq!(err, err); // reflexivity
    }
}
*/

//_! Implementation of RSA encryption algorithm using only the Rust standard library.
//_! For demonstration purposes only – not secure for real-world use.
//_! Assumes availability of trusted prime numbers (obtained externally).
//_! Uses u64 for all values; intermediate multiplications use u128 to avoid overflow.

/// Structure representing an RSA key pair.
#[cfg(test)]
pub struct RsaTest {
    n: u64, // modulus (product of p and q)
    e: u64, // public exponent (usually 65537)
    d: u64, // private exponent
}
#[cfg(test)]
impl RsaTest {
    /// Creates a new RSA instance from two prime numbers `p` and `q`.
    /// The public exponent `e` is fixed to 65537.
    /// Returns `Err` if the provided primes are invalid (e.g., equal, or (p-1)*(q-1) not
    /// coprime with e).
    pub fn new(p: u64, q: u64) -> Result<Self, &'static str> {
        if p == q {
            return Err("p and q must be different");
        }
        let n = p * q;
        let phi = (p - 1) * (q - 1); // Euler's totient

        // Commonly used public exponent
        let e = 65537;

        // Ensure e is coprime with phi
        if Self::gcd(phi, e) != 1 {
            return Err("e and φ(n) are not coprime");
        }

        // Compute private exponent d = e⁻¹ mod φ(n)
        let d = match Self::mod_inv(e, phi) {
            Some(val) => val,
            None => return Err("modular inverse not found"),
        };

        Ok(Self { n, e, d })
    }

    /// Encrypts a plaintext message `m` (must be less than `n`).
    /// Returns ciphertext.
    pub fn encrypt(e: u64, n: u64, m: u64) -> u64 {
        Self::mod_pow(m, e, n)
    }

    /// Decrypts a ciphertext `c` (must be less than `n`).
    /// Returns plaintext.
    pub fn decrypt(&self, c: u64) -> u64 {
        Self::mod_pow(c, self.d, self.n)
    }
    ///
    pub fn get_e(&self) -> u64 {
        self.e
    }
    ///
    pub fn get_n(&self) -> u64 {
        self.n
    }

    // ---------- helper functions ----------

    /// Modular exponentiation: (base^exp) % modulus using exponentiation by squaring.
    fn mod_pow(mut base: u64, mut exp: u64, modulus: u64) -> u64 {
        if modulus == 1 {
            return 0;
        }
        let mut result = 1;
        base %= modulus;
        while exp > 0 {
            if exp % 2 == 1 {
                result = ((result as u128) * (base as u128) % (modulus as u128)) as u64;
            }
            base = ((base as u128) * (base as u128) % (modulus as u128)) as u64;
            exp >>= 1;
        }
        result
    }

    /// Computes the greatest common divisor of two numbers.
    fn gcd(mut a: u64, mut b: u64) -> u64 {
        while b != 0 {
            let t = b;
            b = a % b;
            a = t;
        }
        a
    }

    /// Computes the modular inverse of `a` modulo `m` using the extended Euclidean
    /// algorithm. Returns `Some(inverse)` if exists, else `None`.
    fn mod_inv(a: u64, m: u64) -> Option<u64> {
        let (mut t, mut new_t) = (0i64, 1i64);
        let (mut r, mut new_r) = (m as i64, a as i64);
        while new_r != 0 {
            let quotient = r / new_r;
            (t, new_t) = (new_t, t - quotient * new_t);
            (r, new_r) = (new_r, r - quotient * new_r);
        }
        if r > 1 {
            return None; // not invertible
        }
        if t < 0 {
            t += m as i64;
        }
        Some(t as u64)
    }
}

#[cfg(test)]
mod tests_rsa {
    use super::*;

    #[test]
    fn test_rsa_encrypt_decrypt() {
        // Two small primes (for demonstration only – use much larger ones in practice)
        let p = 8811653;
        let q = 9539867;
        let rsa = RsaTest::new(p, q).unwrap();
        let eee = rsa.get_e();
        let nnn = rsa.get_n();
        //
        //
        //
        let message = 123456;
        let cipher = RsaTest::encrypt(eee, nnn, message);

        let plain = rsa.decrypt(cipher);
        assert_eq!(message, plain);
    }

    #[test]
    fn test_invalid_primes() {
        assert!(RsaTest::new(61, 61).is_err()); // equal primes
    }

    #[test]
    fn test_mod_pow() {
        assert_eq!(RsaTest::mod_pow(4, 13, 497), 445); // known example
    }
}

#[cfg(test)]
mod test_for_hand_maker_tester {
    use super::*;
    use crate::t1dumps_struct::DumpHandMaker;
    #[test]
    fn t1_() {
        assert_eq!(hand_maker_tester::<DumpHandMaker>(), Ok(()));
    }
}

#[cfg(test)]
mod tests_atomic_files {
    use super::*;

    #[test]
    fn test_is_initiator() {
        let init = AtomHandFile::InitiatorFileSize(42);
        let pass = AtomHandFile::PassiveFileSize(100);
        assert!(init.is_initiator());
        assert!(!pass.is_initiator());
    }

    #[test]
    fn test_is_passive() {
        let init = AtomHandFile::InitiatorFileSize(42);
        let pass = AtomHandFile::PassiveFileSize(100);
        assert!(pass.is_passive());
        assert!(!init.is_passive());
    }

    #[test]
    fn test_size() {
        assert_eq!(AtomHandFile::InitiatorFileSize(42).size(), 42);
        assert_eq!(AtomHandFile::PassiveFileSize(100).size(), 100);
    }

    #[test]
    fn test_partial_eq() {
        let a = AtomHandFile::InitiatorFileSize(10);
        let b = AtomHandFile::InitiatorFileSize(10);
        let c = AtomHandFile::InitiatorFileSize(20);
        let d = AtomHandFile::PassiveFileSize(10);

        assert_eq!(a, b);
        assert_ne!(a, c);
        assert_ne!(a, d);
        assert_ne!(c, d);
    }
}
